language: objective-c

matrix:
  include:
    - osx_image: xcode8.2
    - osx_image: xcode8.1

# osx_image:
#   matrix:
#     - xcode8.2
#     - xcode8.1

env:
  global:
    - SCAN_SKIP_BUILD=1
  matrix:
    # Define the details for each test suite that should be run
    - SCAN_WORKSPACE="SampleProject/SampleProject.xcworkspace"                           SCAN_SCHEME="VOKCoreDataManager"         SCAN_SDK="iphonesimulator"
    - SCAN_WORKSPACE="SampleProject/SampleProject.xcworkspace"                           SCAN_SCHEME="VOKCoreDataManager-tvOS"    SCAN_SDK="appletvsimulator"
    - SCAN_WORKSPACE="SampleProject/SampleProject.xcworkspace"                           SCAN_SCHEME="VOKCoreDataManager-OSX"     SCAN_SDK="macosx"
    - SCAN_WORKSPACE="SwiftSampleProject/SwiftSampleProject.xcworkspace"                 SCAN_SCHEME="SwiftyVokoder"              SCAN_SDK="iphonesimulator"
    - SCAN_WORKSPACE="Paging Data Source Example/Paging Data Source Example.xcworkspace" SCAN_SCHEME="Paging Data Source Example" SCAN_SDK="iphonesimulator"
script: bundle exec fastlane scan
after_script:
  - bundle exec pod lib lint
git:
  depth: 10000  # For the auto-incrementing build number script to work, we need to clone with a basically-infinite depth.
cache:
  - bundler  # After main-repo builds, save the "bundler" (local Ruby gems) stuff to cache for future builds.
